package edu.fhda.argos;

/**
 * Describes an error trying to validate the report object prior to either (a) execution, or (b) downloading
 * the completed report file generated by Argos.
 * @version 1.0
 * @author Matt Rapczynski
 */
public class InvalidReportException extends Exception {
    
    public InvalidReportException(String message) {
        super(message);
    }
    
}
